export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const QUEUE_PROVIDER = 'QUEUE_PROVIDER';
export const COMPRESS_IMAGE_PROVIDER = 'COMPRESS_IMAGE_PROVIDER';
export const IMAGE_DOWNLOADER_PROVIDER = 'IMAGE_DOWNLOADER_PROVIDER';
export const IMAGE_STORAGE_PROVIDER = 'IMAGE_STORAGE_PROVIDER';
